---
  
- hosts: localhost
  connection: local
  vars:
          packages: ['python-pip', 'virtualenv']
          envs:
                  TZ: 'Pacific/Auckland'
          
  tasks:
          - name: Install Docker
            apt:
                    name: docker.io
                    state: latest
          - name: Install Pip
            apt:
                    name: "{{ packages }}"
                    state: latest
          - name: Install docker module for Python
            pip:
                    name: docker
          - name: Grab OpenVPN container.
            docker_image:
                    name: linuxserver/openvpn-as
          - name: Run OpenVPN container.
            docker_container:
                    name: openvpn
                    image: linuxserver/openvpn-as
                    state: started
                    ports:
                            - "0.0.0.0:943:943"
                            - "0.0.0.0:9443:9443"
                            - "0.0.0.0:1194:1194/udp"
                    env: "{{ envs }}"
                    restart_policy: unless-stopped
                    cap_add:
                            - NET_ADMIN
