---
  
- hosts: localhost
  connection: local
  vars:
          packages: ['python-pip', 'virtualenv']
          index_src: "/home/ubuntu/git/ansible/apache2/index.html"
          envs:
                  POSTGRES_PASSWORD: 'Th1sisthebestwaytostorepasswords!'
  tasks:
          - name: Install Docker
            apt:
                    name: docker.io
                    state: latest
          - name: Install Pip
            apt:
                    name: "{{ packages }}"
                    state: latest
          - name: Install docker module for Python
            pip:
                    name: docker
          - name: Grab postgres container.
            docker_image:
                    name: postgres
          - name: Run postgres container.
            docker_container:
                    name: postgres
                    image: postgres
                    state: started
                    env: "{{ envs }}"
                    ports:
                            - "0.0.0.0:5432:5432"
